version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.15.1
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: "Run Test Suite"
          environment:
            JEST_JUNIT_OUTPUT: coverage/test-reporter.xml
          command: yarn test:coverage"
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage

workflows:
  build-and-test:
    jobs:
      - build-and-test