version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/node:16.15.1
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image: cimg/node:16.15.1
    steps:
      - run:
          name: "Run Test Suite"
          environment:
            JEST_JUNIT_OUTPUT: coverage/junit.xml
          command: yarn test:coverage
  report:
    docker:
      - image: cimg/node:16.15.1
    steps:
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage

workflows:
  validate-gate:
    jobs:
      - build
      - test:
          requires:
            - build
      - report:
          requires:
            - test