version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  checkout:
    docker:
      - image: cimg/node:16.15.1
    working_directory: ~/movies-selector-app
    steps:
      - checkout
      - save_cache:
          key: v2-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/movies-selector-app

  build:
    docker:
      - image: cimg/node:16.15.1
    working_directory: ~/movies-selector-app
    steps:
      - restore_cache:
          keys:
            - v2-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: v2-dependencies-{{ checksum "package.json" }}
          paths:
            - ~/movies-selector-app/node_modules

  test:
    docker:
      - image: cimg/node:16.15.1
    working_directory: ~/movies-selector-app
    steps:
      - restore_cache:
          keys:
            - v2-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
      - run:
          name: "Run Test Suite"
          environment:
            JEST_JUNIT_OUTPUT: coverage/junit.xml
          command: yarn test:coverage
      - save_cache:
          key: v2-coverage-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/movies-selector-app/coverage
  
  lint:
    docker:
      - image: cimg/node:16.15.1
    working_directory: ~/movies-selector-app
    steps:
      - restore_cache:
          keys:
            - v2-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
      - run:
          name: "Run Linter"
          command: yarn lint:all
      - save_cache:
          key: v2-coverage-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/movies-selector-app/coverage
  
  report:
    docker:
      - image: cimg/node:16.15.1
    working_directory: ~/movies-selector-app
    steps:
      - restore_cache:
          keys:
            - v2-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
      - restore_cache:
          keys:
            - v2-coverage-{{ checksum "package.json" }}
      - store_test_results:
          path: ~/movies-selector-app/coverage
      - store_artifacts:
          path: ~/movies-selector-app/coverage

workflows:
  version: 2
  validate-gate:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
      - report:
          requires:
            - test
            - lint