#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

green='\033[0;32m'
yellow='\033[0;33m'
no_color='\033[0m'

echo -e "\n${yellow}Executing pre-commit hook${no_color}\n"

echo "Execute Validate Version Publish"
#npm run validate-publish-version

echo "Execute Prettier"
npm run format

echo "Execute Lint Staged"
#npx lint-staged

echo -e "${green}Git hook was SUCCESSFUL!${no_color}\n"